# Scan the repo for secrets using betterleaks
# https://github.com/betterleaks/betterleaks

name: "Secrets Scanner"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
jobs:
  scan:
    name: betterleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Scan for Secrets
        uses: dortort/betterleaks-action@v0.1.0
        id: betterleaks
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
