# Scan the repo for secrets using betterleaks
# https://github.com/betterleaks/betterleaks

name: "Secrets Scanner"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
jobs:
  scan:
    name: betterleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # @v7
        with:
          fetch-depth: 0
      - name: Scan for Secrets
        uses: dortort/betterleaks-action@cd0b905aa4befb8f42f8b1ab98150180c9e77515 # @v0.1.0
        id: betterleaks
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
